ALTER TABLE `cv` 
  MODIFY COLUMN `RATE` DECIMAL (6, 4) NULL DEFAULT NULL AFTER `TERM`,
  MODIFY COLUMN `AMOUNT` DECIMAL (10, 2) NULL DEFAULT NULL AFTER `BANK_TITLE`,
  MODIFY COLUMN `LOAN_AMT` DECIMAL (10, 2) NULL DEFAULT NULL AFTER `RELEASE_NO`,
  MODIFY COLUMN `INT_RATE` DECIMAL (6, 4) NULL DEFAULT NULL AFTER `PAYMENT`,
  MODIFY COLUMN `POSTED` TINYINT (1) NULL DEFAULT NULL AFTER `DESC` ;

ALTER TABLE `jv` 
  MODIFY COLUMN `RATE` DECIMAL (6, 4) NULL DEFAULT NULL AFTER `TERM`,
  MODIFY COLUMN `AMOUNT` DECIMAL (10, 2) NULL DEFAULT NULL AFTER `BANK_TITLE`,
  MODIFY COLUMN `LOAN_AMT` DECIMAL (10, 2) NULL DEFAULT NULL AFTER `RELEASE_NO`,
  MODIFY COLUMN `INT_RATE` DECIMAL (6, 4) NULL DEFAULT NULL AFTER `PAYMENT`,
  MODIFY COLUMN `POSTED` TINYINT (1) NULL DEFAULT NULL AFTER `DESC` ;
  
ALTER TABLE `or`
  MODIFY COLUMN `RATE`  DECIMAL(6,4) NULL DEFAULT NULL AFTER `TERM`;
  
ALTER TABLE `slbal` 
  MODIFY COLUMN `RATE` DECIMAL (6, 4) NULL DEFAULT NULL AFTER `TERM`,
  MODIFY COLUMN `INT_RATE` DECIMAL (6, 4) NULL DEFAULT NULL AFTER `PAYMENT` ;
  
ALTER TABLE `loan_products` 
  MODIFY COLUMN `AnnualInterestRate` DECIMAL (6, 4) NOT NULL AFTER `MaximumTerm`,
  MODIFY COLUMN `MinimumLoanableAmount` DECIMAL (10, 2) NOT NULL AFTER `LoanType`,
  MODIFY COLUMN `MaximumLoanableAmount` DECIMAL (10, 2) NOT NULL AFTER `MinimumLoanableAmount` ;

